// -------------------------------------------------------
// Automatically generated with Kodeo's Reegenerator for NON-COMMERCIAL USE
// Generator: RgenTemplate (internal)
// Generation date: 2014-06-07 02:57
// Generated by: GTS-DEV\Pranolo
//-------------------------------------------------------
namespace RgenLib.Templates
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reegenerator", "2.0.6.0")]
    [Kodeo.Reegenerator.Generators.TemplateDisplayAttribute(DisplayName="DbSet", Description="DbSet", HideInDialog=false)]
    public partial class DbSet : Kodeo.Reegenerator.Generators.CodeRenderer
    {
    }
}
