// -------------------------------------------------------
// Automatically generated with Kodeo's Reegenerator for NON-COMMERCIAL USE
// Generator: RgenTemplate (internal)
// Generation date: 2014-06-07 12:56
// Generated by: GTS-DEV\Pranolo
//-------------------------------------------------------
namespace RgenLib.Templates
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reegenerator", "2.0.6.0")]
    [Kodeo.Reegenerator.Generators.TemplateDisplayAttribute(DisplayName="PropertyNameEnum", Description="PropertyNameEnum", HideInDialog=false)]
    public partial class PropertyNameEnum : RgenLib.TaggedCodeRenderer
    {
        
        /// <summary>
        ///Renders the code as defined in the source script file.
        ///</summary>
        ///<param name="output">The instance where the rendered code will be written to.</param>
        ///<param name="PropertyInfos"></param>
        ///<param name="AsInnerClass"></param>
        public virtual void GenEnum(System.IO.StringWriter output, PropertyInfo[] PropertyInfos, bool AsInnerClass)
        {
            output.Write("public static class PropertyNames {\r\n");
 	foreach(var prop in PropertyInfos) { 
            output.Write("\r\n\tpublic const ");
            output.Write( prop.PropertyType.ToString()  );
            output.Write(" ");
            output.Write( prop.Name );
            output.Write(" = \"");
            output.Write( prop.Name );
            output.Write("\";\r\n");
 } 
            output.Write("\r\n}");
            output.WriteLine();
        }
    }
}
