using System;
using System.Xml.Linq;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using RgenLib.TaggedSegment.Json;

namespace RgenLib.TaggedSegment {
    public partial class Manager<T> where T : TaggedCodeRenderer, new() {
        /// <summary>
        /// A superset of OptionAttribute, containing other information generated by the renderer
        /// </summary>
        [JsonObject(MemberSerialization.OptIn)]
        public abstract class Tag {
            protected Tag() {
                RegenMode = RegenModes.Never;
            }
            public const string TagName = "Gen";

            public const string RendererAttributeName = "Renderer";

            private const string RegenModePropertyName = "Regen";
            private const string CategoryPropertyName = "Cat";
            private const string VersionPropertyName = "V";
            public const string GenerateDatePropertyName = "Date";
            private const string TriggerPropertyName = "Trig";
            public const string TemplateNamePropertyName = "Template";
            // ReSharper disable once StaticFieldInGenericType
            static XElement _TagPrototype;
            public static XElement TagPrototype {
                get {
                    if (_TagPrototype == null) {

                        _TagPrototype = new XElement(Tag.TagName);
                        _TagPrototype.Add(new XAttribute(Tag.RendererAttributeName, typeof(T).Name));
                    }
                    return _TagPrototype;
                }
            }

            [JsonProperty(PropertyName = TriggerPropertyName)]
            [XmlAttribute(TriggerPropertyName)]
            public TriggerInfo Trigger { get; set; }

            // ReSharper disable once StaticFieldInGenericType
            private static readonly string _templateName = typeof(T).Name;
            [JsonProperty(TemplateNamePropertyName)]
            public string TemplateName { get { return _templateName; } }
            public T OptionAttribute { get; set; }

            [JsonProperty(PropertyName = CategoryPropertyName)][XmlAttribute(CategoryPropertyName)]
            public string Category { get; set; }

            [JsonProperty(PropertyName = RegenModePropertyName)][XmlAttribute(RegenModePropertyName)]
            [JsonConverter(typeof(StringEnumConverter))]
            public RegenModes RegenMode { get; set; }

            public TagTypes TagType { get; set; }

            [JsonConverter(typeof(RgenLib.TaggedSegment.Json.VersionConverter))]
            [JsonProperty(PropertyName = VersionPropertyName)][XmlAttribute(VersionPropertyName)]
            public Version Version { get; set; }

            [JsonProperty(PropertyName = GenerateDatePropertyName)][XmlAttribute(GenerateDatePropertyName)]
            public DateTime? GenerateDate { get; set; }
            /// <summary>
            /// Allow access to protected MemberwiseClone();
            /// </summary>
            /// <returns></returns>
            public new virtual Tag MemberwiseClone() {
                return (Tag)base.MemberwiseClone();
            }




        }
    }
}
